# Generated by Django 5.2.16 on 2026-08-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_quote_delivery_lat_quote_delivery_lng_quote_distance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='delivery_city',
            field=models.CharField(default='Unknown', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='pickup_city',
            field=models.CharField(default='Unknown', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quote',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='quote',
            name='transport_type',
            field=models.CharField(choices=[('open', 'Open Transport'), ('enclosed', 'Enclosed Transport')], max_length=50),
        ),
        migrations.AlterField(
            model_name='quote',
            name='vehicle_condition',
            field=models.CharField(choices=[('running', 'Running Vehicle'), ('non_running', 'Non-Running Vehicle')], max_length=50),
        ),
    ]
