# Generated by Django 5.2.16 on 2026-08-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_quote_delivery_city_quote_pickup_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='vehicle_type',
            field=models.CharField(default='as soon as possible', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='pickup_date',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
