# Generated by Django 5.2.16 on 2026-08-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_quote_vehicle_type_alter_quote_pickup_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
